export const ADD_READING_LIST = 'ADD_READING_LIST';
export const DELETE_READING_LIST = 'DELETE_READING_LIST';

export const GET_NEWS_DATA = 'GET_NEWS_DATA';
export const SUCCESS_GET_NEWS_DATA = 'SUCCESS_GET_NEWS_DATA';
export const FAILED_GET_NEWS_DATA = 'FAILED_GET_NEWS_DATA';

